version: "3.8"
services:
  marinanote:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - ADMIN_USER
      - ADMIN_PASS
      - ADMIN_PATH
      - NOTES_PATH
      - SESSION_SECRET
      - PORT
      - SITE_NAME
      - AUTH_MODE
      - HCAPTCHA_SITEKEY
      - HCAPTCHA_SECRET
      - CF_TURNSTILE_SITEKEY
      - CF_TURNSTILE_SECRET
      - F2A_SECRET
      - MAX_UPLOAD_MB
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped